### ISSUE TITLE
Port the "queue" design recipe from official bindings

### ISSUE THREAD

**Issue by PierreZ** [foundationdb-rs/foundationdb-rs#124]
As our efforts to provide all the [design recipes](https://apple.github.io/foundationdb/design-recipes.html) in rust, we should add "queue" as an example. 

This is a simple port of the [java implementation](https://apple.github.io/foundationdb/queues-java.html), as their API is more close to the Rust bindings.

## TODOs

* Convert the example from Java to Rust and put it in [foundationdb/examples](https://github.com/foundationdb-rs/foundationdb-rs/tree/main/foundationdb/examples)
* Make it work
* Cargo clippy / fmt
* Should be runned by the CI automatically [without changes](https://github.com/foundationdb-rs/foundationdb-rs/blob/9d7488d7bd836978df43bad4960dc10c3d0268e7/.github/workflows/ci.yml#L97)

**Comment by b4D8** [comment]
Closed by #125.
