### ISSUE TITLE
Any plans to support additional APIs

### ISSUE THREAD

**Issue by Rjerk** [foundationdb-rs/foundationdb-rs#130]
Some C APIs like `fdb_database_get_main_thread_busyness` are not ported. Do you have any plans to work with that?

**Comment by PierreZ** [comment]
Hi :wave: 

I somehow missed that API, it could be really useful. Do you want to contribute to the repo?

**Comment by Rjerk** [comment]
Yes. I just recently started learning rust. I used this crate to write a prototype and found some useful functions were missing. I'm happy to contribute to this repository but I may need your help reviewing it.
