### ISSUE TITLE
Introduce platform support

### ISSUE THREAD

**Issue by PierreZ** [foundationdb-rs/foundationdb-rs#4]
As the FDB community is officially discontinuing the Windows build(see apple/foundationdb#5135 for more info), we should clarify our posture towards platform like Windows, Apple Silicon and so on.

One way to handle this can be to introduce platform support tiers, like in Rust:

* Tier 1 targets can be thought of as "guaranteed to work", meaning that the bindingtester is running on it to check correctness,
* Tier 2 targets can be thought of as "guaranteed to build", meaning that CI are running some tests on it.

What do you think about this?

**Comment by Speedy37** [comment]
I agree.
About windows, might be great to find a way to have it tier 2 at some point.

**Comment by PierreZ** [comment]
> I agree. About windows, might be great to find a way to have it tier 2 at some point.

I agree, we should include a Tier 3 with platforms that we would live to have in Tier 2.

 I think we can start with something like this:

* Tier 1: `linux x86_64`,
* Tier 2: `macos x86_64`
* Tier 3: `windows x86_64`, `apple silicon`

**Comment by PierreZ** [comment]
Closed in #15
