### ISSUE TITLE
Publish `0.6.0` on crates.io

### ISSUE THREAD

**Issue by PierreZ** [foundationdb-rs/foundationdb-rs#40]
As soon as #38 is fixed, we should release the current version to crates.io.

From what I can see, @yjh0502, @bluejekyll and @Speedy37 are listed as owners in the [crate page](https://crates.io/crates/foundationdb). 

Could you add me as owner of the crate? Or we could setup [a Github Team](https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-owner) to ease management. WDYT?

**Comment by bluejekyll** [comment]
I think I already transferred ownership. I believe that information is from the Cargo.toml.

**Comment by PierreZ** [comment]
> I think I already transferred ownership. I believe that information is from the Cargo.toml.

Mmmh, I'm sorry for the ping then, please ignore :pray:

**Comment by Speedy37** [comment]
bluejekyll and yjh0502 are owners of the 3 crates
@PierreZ have you checked https://crates.io/me/pending-invites

**Comment by PierreZ** [comment]
Thanks @Speedy37 :tada: 
I'll publish 0.6.0 next week if no faulty seeds are found by the correctness-tests.
