### ISSUE TITLE
Query issue

### ISSUE THREAD

**Issue by cisaacson** [foundationdb-rs/foundationdb-rs#71]
We have a process performing many range queries using Transaction.get_range. Each query has a limit of 50 rows. At some point mid-way through processing the query returned only 1 row instead of the expected 50 (there were 1000s of rows left in the range). The query uses the default Iterator streaming mode; we tried WantAll too but it did the same thing. This is using version `0.6.0` of the library, running the `6.3.23` version of FoundationDb. I have never seen this occur in years of usage. What is even more puzzling is that we took that specific query with exactly the same keys and ran it through a testing tool we built (also using this library and version) and it worked perfectly. It's only when we did it in a big loop that it didn't bring back all we expected.

I suspect that this is because we never implemented `GetRangeResult.next` to check if there are more results. 2 questions:

* Could not checking `GetRangeResult.next` cause this, as sometimes with heavier load the number of result rows that come back can be less than what was requested?
* Can the same thing happen with the `WantAll` mode? We did see exactly the same behavior with this. If so we'll go back to `Iterator` mode and implement `GetRangeResult.next` as documented.

**Comment by cisaacson** [comment]
@PierreZ Thank you very much for the quick response.

And we love this crate, FoundationDb + Rust is an awesome combination, very powerful. Thanks for all the work on it. If you need documentation help that is something I could look at.

**Comment by PierreZ** [comment]
> @PierreZ I closed the issue a bit too soon :).
> 
> Right now we have code that works like this:
> 
> ```
> let values = tx
>             .get_range(&range_option, 1, false)
>             .await
>             .map_err(|e| DbError::new(&format!("{}", e)))?;
> 
>         for key_value in &values {
>             let key = key_value.key();
>             let value = key_value.value();
> 
> ...
> ```
> 
> Can you show an example of how to use `get_ranges` or `get_ranges_keyvalues` to achieve the same thing? We just need to iterate over the result and we then add it to a Vec.
> 
> Thanks again for the help.

I think something like this should work:

```rust
let _keys: Vec<FdbValue> = trx
    .get_range(&range_option, false)
    .await
    .try_collect()
    .await?;
```

**Comment by cisaacson** [comment]
Thanks @PierreZ . 

For reference for others it works well this way:
```
let values: Vec<FdbValue> = tx
            .get_ranges_keyvalues(range_option, false)
            .try_collect()
            .await?;
```

The `get_ranges_keyvalues` is the full fn name, and it does not return a Future, so the first`await` is not necessary.

This works great, much simpler than the alternative.
